class Lexicon:
    informed_consent = "Informed Consent/Informierte Zustimmung"
    structure_exp = "Structure of the Experiment"
    end_part_i_ii = "End of Part I and II"
    hl = "Holt Laury Risk Elicitation Task"
    part_ii_welcome = "Welcome to Part II"
    part_i_welcome = "Welcome to Part I"
    survey = "Survey"
    results = "Investment Game Results"
    gneezy_potters = "Investment Game"
    no_answer = "Prefer not to say"
    high_school = "High School"
    bachelors = "Bachelor's"
    masters = "Master's"
    phd = "PhD"
    other = "Other"
    public_insurance = "Statutory insurance"
    private_insurance = "Private insurance"
    sure_payment = "Sure payment"
    female = "Female"
    male = "Male"
    yes = "Yes"
    no = "No"
    diverse = "Diverse"
    not_a_student = "Not a student"

